
package main;

import java.util.Random;

public class Main_jFrame extends javax.swing.JFrame {
    Shotgun shotgun = new Shotgun();
    Random rand = new Random();
    int lives = 5;
    int dLives = 10;
    int[] pwrs = {-1,-1,-1,-1};
    String[] powerUps = {"/main/magnify.jpg","/main/lives.jpg","/main/cola.jpg","/main/phone.jpg","/main/invert.jpg"};
    boolean turn = true;
    Instructions_jFrame ins = new Instructions_jFrame();
    
    /**
     * Creates new form Main_jFrame
     */
    public Main_jFrame() {
        initComponents();
        int rando = rand.nextInt(4,9);
        shotgun.reload(rando);
        jLabel5.setText(""+shotgun.print()+" live and "+(shotgun.num-shotgun.print())+" blank");
        jButton1.setVisible(false);
        jButton3.setVisible(false);
        
        rando = rand.nextInt(0,5);
        jButton4.setVisible(true);
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource(powerUps[rando])));
        pwrs[0] = rando;
        
        rando = rand.nextInt(0,5);
        jButton5.setVisible(true);
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource(powerUps[rando])));
        pwrs[1] = rando;
        
        jButton6.setVisible(false);
        jButton7.setVisible(false);      
        jButton8.setVisible(false);
        jLabel4.setText("your turn");
        update();
        ins.setLocationRelativeTo(null);
        ins.setAlwaysOnTop( true );
        ins.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/mr-fresh.jpg"))); // NOI18N

        jButton1.setText("Dealer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/shotgun.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("You");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jButton8.setText("OK");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(jButton3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(184, 184, 184)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(253, 253, 253))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton8)
                                                .addGap(120, 120, 120)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jButton6)
                                    .addComponent(jButton7))))
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel5)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel7))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addContainerGap())
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(15, 15, 15)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jButton8)))
                        .addGap(13, 13, 13))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jButton7.setVisible(false);
        if(pwrs[3]==0){
            int status = shotgun.inspect();
            if(status ==1){
                jLabel5.setText("Its live");
            }
            else{
                jLabel5.setText("Its a blank");
            }
        }
        else if(pwrs[3]==1){
            lives++;
            jLabel5.setText("healed 1 life");
            jLabel2.setText("lives "+lives);
        }
        else if(pwrs[3]==2){
            int status = shotgun.rack();
            if(status ==1){
                jLabel5.setText("Ejected a live round");
            }
            else{
                jLabel5.setText("Ejected a blank");
            }
        }
        else if(pwrs[3]==3){
            jLabel5.setText(shotgun.phone());
        }
        else{
            jLabel5.setText("inverted polarity of current bullet");
            shotgun.invert();
        }
        pwrs[3] = -1;
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jButton4.setVisible(false);
        if(pwrs[0]==0){
            int status = shotgun.inspect();
            if(status ==1){
                jLabel5.setText("Its live");
            }
            else{
                jLabel5.setText("Its a blank");
            }
        }
        else if(pwrs[0]==1){
            lives++;
            jLabel5.setText("healed 1 life");
            jLabel2.setText("lives "+lives);
        }
        else if(pwrs[0]==2){
            int status = shotgun.rack();
            if(status ==1){
                jLabel5.setText("Ejected a live round");
            }
            else{
                jLabel5.setText("Ejected a blank");
            }
        }
        else if(pwrs[0]==3){
            jLabel5.setText(shotgun.phone());
        }
        else{
            jLabel5.setText("inverted polarity of current bullet");
            shotgun.invert();
        }
        pwrs[0] = -1;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel5.setText("");
        jButton2.setVisible(false);
        jButton1.setVisible(true);
        jButton3.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton2.setVisible(false);
        jButton1.setVisible(false);
        jButton3.setVisible(false);
        jButton8.setVisible(true);
        if(shotgun.shoot()==1){
            dLives--;
            turn = false;
            jLabel4.setText("you shot dealer");
            jLabel3.setText("dealer's lives "+dLives);
        }
        else{
            turn = false;
            jLabel4.setText("shame. it was blank");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton2.setVisible(false);
        jButton1.setVisible(false);
        jButton3.setVisible(false);
        jButton8.setVisible(true);
        if(shotgun.shoot()==1){
            lives--;
            turn = false;
            jLabel4.setText("you shot yourself lol");
            jLabel2.setText("lives "+lives);
        }
        else{
            turn = true;
            jLabel4.setText("it was a blank. you get to go again");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jLabel5.setText("");
        if(turn){
            jButton2.setVisible(true);
            jButton8.setVisible(false);
            jLabel4.setText("your turn");
            update();
        }
        else{
            
            update();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jButton5.setVisible(false);
        if(pwrs[1]==0){
            int status = shotgun.inspect();
            if(status ==1){
                jLabel5.setText("Its live");
            }
            else{
                jLabel5.setText("Its a blank");
            }
        }
        else if(pwrs[1]==1){
            lives++;
            jLabel5.setText("healed 1 life");
            jLabel2.setText("lives "+lives);
        }
        else if(pwrs[1]==2){
            int status = shotgun.rack();
            if(status ==1){
                jLabel5.setText("Ejected a live round");
            }
            else{
                jLabel5.setText("Ejected a blank");
            }
        }
        else if(pwrs[1]==3){
            jLabel5.setText(shotgun.phone());
        }
        else{
            jLabel5.setText("inverted polarity of current bullet");
            shotgun.invert();
        }
        pwrs[1] = -1;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jButton6.setVisible(false);
        if(pwrs[2]==0){
            int status = shotgun.inspect();
            if(status ==1){
                jLabel5.setText("Its live");
            }
            else{
                jLabel5.setText("Its a blank");
            }
        }
        else if(pwrs[2]==1){
            lives++;
            jLabel5.setText("healed 1 life");
            jLabel2.setText("lives "+lives);
        }
        else if(pwrs[2]==2){
            int status = shotgun.rack();
            if(status ==1){
                jLabel5.setText("Ejected a live round");
            }
            else{
                jLabel5.setText("Ejected a blank");
            }
        }
        else if(pwrs[2]==3){
            jLabel5.setText(shotgun.phone());
        }
        else{
            jLabel5.setText("inverted polarity of current bullet");
            shotgun.invert();
        }
        pwrs[2] = -1;
    }//GEN-LAST:event_jButton6ActionPerformed
    
    public void update(){
        jLabel2.setText("lives "+lives);
        jLabel3.setText("dealer's lives "+dLives);
        if(shotgun.num ==0){
            int rando = rand.nextInt(4,9);
            shotgun.reload(rando);
            jLabel5.setText(""+shotgun.print()+" live and "+(shotgun.num-shotgun.print())+" blank");
            for(int k = 0;k<4;k++){
                if(pwrs[k]==-1){
                    rando = rand.nextInt(0,5);
                    pwrs[k] = rando;
                    if(k ==0){
                        jButton4.setVisible(true);
                        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource(powerUps[rando])));
                    }
                    else if(k ==1){
                        jButton5.setVisible(true);
                        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource(powerUps[rando])));
                    }
                    else if(k ==2){
                        jButton6.setVisible(true);
                        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource(powerUps[rando])));
                    }
                    else{
                        jButton7.setVisible(true);
                        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource(powerUps[rando])));
                    }
                    break;
                }
            }
            for(int k = 0;k<4;k++){
                if(pwrs[k]==-1){
                    rando = rand.nextInt(0,5);
                    pwrs[k] = rando;
                    if(k ==0){
                        jButton4.setVisible(true);
                        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource(powerUps[rando])));
                    }
                    else if(k ==1){
                        jButton5.setVisible(true);
                        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource(powerUps[rando])));
                    }
                    else if(k ==2){
                        jButton6.setVisible(true);
                        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource(powerUps[rando])));
                    }
                    else{
                        jButton7.setVisible(true);
                        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource(powerUps[rando])));
                    }
                    break;
                }
            }
        }

        if(turn==false){
            jButton2.setVisible(false);
            jButton1.setVisible(false);
            jButton3.setVisible(false);
            if(shotgun.front ==null){
                turn = true;
                update();
            }
            
            int shootWho = rand.nextInt(0,2);
            if(shootWho ==1){
                turn = true;
                if(shotgun.shoot()==1){
                    lives--;
                    jLabel4.setText("dealer shot you");
                }
                else{
                    jLabel4.setText("you were lucky it was a blank");
                }
            }
            else{
                if(shotgun.shoot()==1){
                    dLives--;
                    turn = true;
                    jLabel4.setText("dealer shot himself lol");
                }
                else{
                    jLabel4.setText("dealer shot himself with a blank");
                }
            }
            if(turn){
                jButton8.setVisible(true);
                update();
            }
        }
        
        if(lives <=0){
                jButton1.setVisible(false);
                jButton2.setVisible(false);
                jButton3.setVisible(false);
                jButton4.setVisible(false);
                jButton5.setVisible(false);
                jButton6.setVisible(false);
                jButton7.setVisible(false);
                jButton8.setVisible(false);
                jLabel2.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setText("You Lose");
                jLabel5.setVisible(false);
        }
        if(dLives <=0){
                jButton1.setVisible(false);
                jButton2.setVisible(false);
                jButton3.setVisible(false);
                jButton4.setVisible(false);
                jButton5.setVisible(false);
                jButton6.setVisible(false);
                jButton7.setVisible(false);
                jButton8.setVisible(false);
                jLabel2.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setText("You Win");
                jLabel5.setVisible(false);
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_jFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
